-- ALIGNMENT SCRIPT: User Schema + Granular Fields + RLS

-- 1. Ensure Columns Exist (User Schema + Granular Fields)
-- Base Fields
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS full_name varchar(255);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS mobile_number varchar(20);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS email varchar(255);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS created_at timestamp default now();
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS updated_at timestamp default now();
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS source varchar(20) DEFAULT 'web';

-- Address Fields (Base & Granular)
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS address text; -- Maps to address_line1
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS door_no text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS street text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS landmark text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS district text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS city varchar(100);
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS state text;
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS pincode text; -- Maps to postal_code

-- Contact
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS alternative_mobile text;

-- Auth Link
ALTER TABLE public.customers ADD COLUMN IF NOT EXISTS auth_id uuid REFERENCES auth.users(id) ON DELETE CASCADE;

-- 2. Constraints & Indexes (As per User Request)

-- Check Constraint for Source (Allows 'whatsapp' and 'web' as per your schema)
DO $$ BEGIN
    ALTER TABLE public.customers ADD CONSTRAINT customers_source_check 
    CHECK (source IN ('whatsapp', 'web'));
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_customers_auth_id ON public.customers (auth_id);
CREATE INDEX IF NOT EXISTS idx_customers_email ON public.customers (email);

-- Unique Constraint: Whatsapp Mobile
CREATE UNIQUE INDEX IF NOT EXISTS customers_whatsapp_mobile_unique ON public.customers (mobile_number)
WHERE source = 'whatsapp' AND mobile_number IS NOT NULL;

-- Unique Constraint: Web Email
CREATE UNIQUE INDEX IF NOT EXISTS customers_web_email_unique ON public.customers (email)
WHERE source = 'web' AND email IS NOT NULL;

-- Unique Constraint: Auth ID
CREATE UNIQUE INDEX IF NOT EXISTS customers_auth_id_unique ON public.customers (auth_id)
WHERE auth_id IS NOT NULL;

-- 3. Wishlist RLS Policies & Table Setup
CREATE TABLE IF NOT EXISTS public.wishlist (
  id bigint generated by default as identity primary key,
  customer_id bigint references public.customers(customer_id) on delete cascade not null,
  variant_id bigint not null, -- references product_variants, assume exists
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(customer_id, variant_id)
);

ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own wishlist
DROP POLICY IF EXISTS "Users can view their own wishlist" ON public.wishlist;
CREATE POLICY "Users can view their own wishlist" 
ON public.wishlist FOR SELECT 
USING (
    customer_id IN (
        SELECT customer_id FROM public.customers 
        WHERE auth_id = auth.uid()
    )
);

-- Allow users to add to their own wishlist
DROP POLICY IF EXISTS "Users can add to their own wishlist" ON public.wishlist;
CREATE POLICY "Users can add to their own wishlist" 
ON public.wishlist FOR INSERT 
WITH CHECK (
    customer_id IN (
        SELECT customer_id FROM public.customers 
        WHERE auth_id = auth.uid()
    )
);

-- Allow users to remove from their own wishlist
DROP POLICY IF EXISTS "Users can remove from their own wishlist" ON public.wishlist;
CREATE POLICY "Users can remove from their own wishlist" 
ON public.wishlist FOR DELETE 
USING (
    customer_id IN (
        SELECT customer_id FROM public.customers 
        WHERE auth_id = auth.uid()
    )
);

-- 4. Storage Policies for Profile Photos
-- Create bucket if not exists
INSERT INTO storage.buckets (id, name, public)
VALUES ('customer-profiles', 'customer-profiles', true)
ON CONFLICT (id) DO NOTHING;

-- Policy: Public Read Access
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access"
ON storage.objects FOR SELECT
USING ( bucket_id = 'customer-profiles' );

-- Policy: Authenticated Upload
DROP POLICY IF EXISTS "Authenticated users can upload profile photos" ON storage.objects;
CREATE POLICY "Authenticated users can upload profile photos"
ON storage.objects FOR INSERT
WITH CHECK (
    bucket_id = 'customer-profiles' AND
    auth.role() = 'authenticated'
);

-- Policy: Users can update their own files
DROP POLICY IF EXISTS "Users can update their own profile photos" ON storage.objects;
CREATE POLICY "Users can update their own profile photos"
ON storage.objects FOR UPDATE
USING (
    bucket_id = 'customer-profiles' AND
    auth.uid() = owner
);

-- Policy: Users can delete their own files
DROP POLICY IF EXISTS "Users can delete their own profile photos" ON storage.objects;
CREATE POLICY "Users can delete their own profile photos"
ON storage.objects FOR DELETE
USING (
    bucket_id = 'customer-profiles' AND
    auth.uid() = owner
);
