-- Enhanced Query System - Database Schema
-- Run this in Supabase SQL Editor

-- =====================================================
-- STEP 1: Add source column to queries table
-- =====================================================
ALTER TABLE queries ADD COLUMN IF NOT EXISTS source VARCHAR(20) DEFAULT 'Web';
-- Values: 'Web' (Email), 'WhatsApp'

-- =====================================================
-- STEP 2: Create query_messages table for conversation threads
-- =====================================================
CREATE TABLE IF NOT EXISTS query_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_id BIGINT NOT NULL REFERENCES queries(query_id) ON DELETE CASCADE,
    sender_type VARCHAR(20) NOT NULL CHECK (sender_type IN ('customer', 'admin')),
    message TEXT NOT NULL,
    sent_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    delivered BOOLEAN DEFAULT FALSE,
    delivery_error TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fast lookup
CREATE INDEX IF NOT EXISTS idx_query_messages_query_id ON query_messages(query_id);
CREATE INDEX IF NOT EXISTS idx_query_messages_sent_at ON query_messages(sent_at DESC);

-- =====================================================
-- STEP 3: Enable RLS for query_messages
-- =====================================================
ALTER TABLE query_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all to view query_messages"
    ON query_messages FOR SELECT USING (true);

CREATE POLICY "Allow all to insert query_messages"
    ON query_messages FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow all to update query_messages"
    ON query_messages FOR UPDATE USING (true);

-- =====================================================
-- STEP 4: Create function to check for duplicates
-- (Instead of unique index, we use a function to handle edge cases)
-- =====================================================
CREATE OR REPLACE FUNCTION check_query_duplicate(
    p_source VARCHAR,
    p_mobile VARCHAR,
    p_email VARCHAR,
    p_order_id VARCHAR
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
DECLARE
    duplicate_count INTEGER;
BEGIN
    IF p_source = 'WhatsApp' THEN
        -- For WhatsApp: check mobile_number + order_id
        SELECT COUNT(*) INTO duplicate_count
        FROM queries
        WHERE source = 'WhatsApp'
          AND mobile_number = p_mobile
          AND COALESCE(order_id, '') = COALESCE(p_order_id, '')
          AND status != 'Closed';
    ELSE
        -- For Web: check email + order_id
        SELECT COUNT(*) INTO duplicate_count
        FROM queries
        WHERE source = 'Web'
          AND email = p_email
          AND COALESCE(order_id, '') = COALESCE(p_order_id, '')
          AND status != 'Closed';
    END IF;
    
    RETURN duplicate_count > 0;
END;
$$;

-- =====================================================
-- STEP 5: Create function to get query with messages
-- =====================================================
CREATE OR REPLACE FUNCTION get_query_with_messages(p_query_id BIGINT)
RETURNS TABLE (
    query_id BIGINT,
    customer_id BIGINT,
    name VARCHAR,
    mobile_number VARCHAR,
    email VARCHAR,
    message TEXT,
    status VARCHAR,
    priority TEXT,
    order_id TEXT,
    remarks TEXT,
    source VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE,
    messages JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    RETURN QUERY
    SELECT 
        q.query_id,
        q.customer_id,
        q.name,
        q.mobile_number,
        q.email,
        q.message,
        q.status,
        q.priority,
        q.order_id,
        q.remarks,
        q.source,
        q.created_at,
        COALESCE(
            (SELECT jsonb_agg(
                jsonb_build_object(
                    'message_id', m.message_id,
                    'sender_type', m.sender_type,
                    'message', m.message,
                    'sent_at', m.sent_at,
                    'delivered', m.delivered
                ) ORDER BY m.sent_at ASC
            ) FROM query_messages m WHERE m.query_id = q.query_id),
            '[]'::jsonb
        ) as messages
    FROM queries q
    WHERE q.query_id = p_query_id;
END;
$$;

GRANT EXECUTE ON FUNCTION get_query_with_messages(BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION get_query_with_messages(BIGINT) TO anon;
GRANT EXECUTE ON FUNCTION check_query_duplicate(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO authenticated;
GRANT EXECUTE ON FUNCTION check_query_duplicate(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO anon;

-- =====================================================
-- STEP 6: Migrate existing messages to query_messages table
-- =====================================================
INSERT INTO query_messages (query_id, sender_type, message, sent_at)
SELECT query_id, 'customer', message, created_at
FROM queries
WHERE message IS NOT NULL AND message != ''
ON CONFLICT DO NOTHING;

-- Done!
SELECT 'Database schema updated successfully!' as status;
